/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as prisma from "./../node_modules/.prisma/client/index"
import { Context } from "./api/context"
import { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  DataTable: prisma.DataTable;
  DataTableConnection: { // root type
    edges?: Array<NexusGenRootTypes['DataTableEdge'] | null> | null; // [DataTableEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  DataTableEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['DataTable'] | null; // DataTable
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  DataTable: { // field return type
    fileKey: string | null; // String
    id: string; // ID!
    name: string | null; // String
    status: string | null; // String
  }
  DataTableConnection: { // field return type
    edges: Array<NexusGenRootTypes['DataTableEdge'] | null> | null; // [DataTableEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  DataTableEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['DataTable'] | null; // DataTable
  }
  Mutation: { // field return type
    createDataTable: NexusGenRootTypes['DataTable']; // DataTable!
    ping: string; // String!
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    dataTables: NexusGenRootTypes['DataTableConnection'] | null; // DataTableConnection
    drafts: Array<NexusGenRootTypes['DataTable'] | null>; // [DataTable]!
    ok: boolean; // Boolean!
  }
}

export interface NexusGenFieldTypeNames {
  DataTable: { // field return type name
    fileKey: 'String'
    id: 'ID'
    name: 'String'
    status: 'String'
  }
  DataTableConnection: { // field return type name
    edges: 'DataTableEdge'
    pageInfo: 'PageInfo'
  }
  DataTableEdge: { // field return type name
    cursor: 'String'
    node: 'DataTable'
  }
  Mutation: { // field return type name
    createDataTable: 'DataTable'
    ping: 'String'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    dataTables: 'DataTableConnection'
    drafts: 'DataTable'
    ok: 'Boolean'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDataTable: { // args
      fileKey: string; // String!
      name: string; // String!
    }
    ping: { // args
      text: string; // String!
    }
  }
  Query: {
    dataTables: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}